Add configmap for grafana dashboard
scalar-labs/helm-charts pull request #13
Opened 2021-08-05 07:49 UTC by tei-k

# Description
https://scalar-labs.atlassian.net/browse/DLT-9612

2021-08-07 01:52 UTC, superbrothers requested changes

2021-08-07 01:52 UTC, superbrothers commented on charts/scalardl/values.yaml
> +    # ledger.grafana_dashboard.namespace -- which namespace grafana dashboard is located. by default monitoring
```suggestion
    # ledger.grafanaDashboard.enabled -- enable grafana dashboard
    enabled: false
    # ledger.grafanaDashboard.namespace -- which namespace grafana dashboard is located. by default monitoring
```

2021-08-07 01:52 UTC, superbrothers commented on charts/scalardl/values.yaml
> +    namespace: monitoring
```suggestion
    # ledger.grafanaDashboard.enabled -- enable grafana dashboard
    enabled: false
    # ledger.grafanaDashboard.namespace -- which namespace grafana dashboard is located. by default monitoring
    namespace: monitoring
```

2021-08-10 00:50 UTC, superbrothers approved these changes

2021-08-11 06:01 UTC, ymorimo approved these changes
LGTM!

2021-08-11 11:25 UTC, feeblefakie approved these changes
LGTM! Thank you!
Left a minor naming suggestion.

2021-08-11 11:25 UTC, feeblefakie commented on charts/scalardl/files/scalardl_grafana_dashboard.json
> +  "title": "Scalar DLT Response",
```suggestion
  "title": "Scalar DL Response",
```

2021-08-11 11:25 UTC, feeblefakie commented on charts/scalardl/files/scalardl_grafana_dashboard.json
> +  "title": "Scalar DLT Response",
@tei-k Applied it by myself.

2021-08-11 11:26 UTC, merged